project:
  type: book
  output-dir: "docs"
  execute-dir: file

book:
  title: "**DRAFT** Climate Change in Montana"
  author: "Colin Brust"
  sidebar:
    style: docked
    background: light
  date: "11/2/2022"
  chapters:
    - index.qmd
    - causes.qmd
    - assessment.qmd
    - historical.qmd
    - teleconnections.qmd
    - future.qmd
    - gaps.qmd
    - conclusions.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt

include-in-header: "./assets/hypothesis.js"
number-sections: true

crossref:
  chapters: true
