# **Draft** Conclusions {#sec-conclusions}
The analysis presented in this chapter shows that statewide, Montana has warmed—up to 1.86°F the between 1951 and 2020 Seasonally, that warming has been greatest in winter (2.9°F) and spring (3.4°F). Montana’s number of frost days has decreased by 6 days since 1951. Statewide, average annual precipitation increeased by 0.12 inches/decade between 1951 and 2020, with variations caused by global climate oscillations, such as El Niño events, explaining some of the historical precipitation variability in parts of the state.

With this historical context, we considered Montana’s future under four shared socioeconomic pathways. Using those pathways, we employed standard modeling techniques available to climate scientists today—ensembles of general circulation models—and projected Montana’s climate over the next century. Our analyses focused on projecting the possible range of temperature and precipitation amounts in Montana, under our chosen greenhouse gas emission scenarios.

> While the model results varied, one message is imminently clear: Montana in the coming century will be a warmer place.

In @tbl-summary we provide a summary of the work done and described in this chapter. In summary, Montana is projected to continue to warm in all geographic locations, seasons, and under all emission scenarios throughout the 21st century. By mid century, Montana temperatures are projected to increase by up to 4.8°F; by the end of the century, temperatures will increase by up to 8.7°F. Projections show that we could have up to 50 more frost-free days at the end of the century. Likewise, frequency of extreme heat will increase. In eastern Montana, for example, we may have more then 45 days/yr in which maximum temperatures exceed 90°F (32°C). 

In mid- and end-of-century projections, average annual precipitation and variability increase across the state, as do winter, spring, and fall precipitation. Summer months, however, show small decreases in precipitation. Current projections suggest slight increases in both dry and wet events.

Montanans must be prepared for projected increases in temperature in the future. Because of its interior location, Montana has warmed more over the last 65 yr than the national average, and it will experience greater warming than most parts of the country in the future, particularly when compared to states in coastal regions. Key to the concern is that coming temperature changes will be larger in magnitude and occur more rapidly than any time since our 1889 declaration of statehood (and, to be sure, well before).

> Montana’s average annual temperature is projected to increase through the end-of-century for all models, all emission scenarios, and in all geographic locations. 

```{r summary_table, echo=FALSE}
#| label: tbl-summary
#| tbl-cap: Summary of climate metrics described in this chapter.
library(magrittr)

tibble::tribble(
  ~`Climate Metric`, ~`Trend and Future Scenario`,
  'Atmospheric CO2 Concentrations', 'Global atmospheric carbon dioxide concentrations have increased over 100 ppm since Montana statehood and are projected to increase under both future scenarios considered here.',
  'Average Temperature', 'Since 1951, average statewide temperatures have increased by 0.27°F/decade, with greatest warming in spring; projected to increase by 3-5°F  by mid century, with greatest warming in summer and winter and in the east',
  'Maximum Temperatures', 'Maximum temperatures have increased most in spring and are projected to increase 3-5°F by mid century.',
  'Days above 90°F', 'Extreme heat days are projected to increase by 10-23 additional days by mid century, with greatest increases in the northeast and south.',
  'Minimum Temperatures', 'Minimum temperatures are projected to increase 3-5°F by mid century.', 
  'Frost-free Days', 'Frost-free days are projected to increase by 18-28 days by mid century, particularly in the west.',
  'Average Precipitation', 'Statewide precipitation has decreased in winter (0.1 inches/decade) since 1951, but annual precipitation has increased by 0.12 inches/decade, driven by increases in spring and fall precipitation. Precipitation is projected to increase, primarily in spring (0.25-0.3 inches; a slight statewide decrease in summer precipitation and increased year-to-year variability of precipitation are projected, as well.',
  'Number of Consecutive Dry Days', 'Projected changes range from 0.5 to 3.1 by end of the century. However, increased variability in precipitation suggests potential for more severe droughts, particularly in connection with climate oscillations.',
  'Number of Consecutive Wet Days', 'Slight increases across all climate divisions and SSP scenarios.'
) %>%
  knitr::kable()

```
