---
params: 
  location: "Montana"
  asset_dir: "./assets"
  attr_id: "Division"
  attr_name: "Climate Division"
  attr_plural: "Climate Divisions"
---

# **Draft** Overview {.unnumbered}
**Throughout this document, numbers that are in bold still need to be updated. **

## An Update to the Montana Climate Analysis

This website is an update to to the climate chapter of the [Montana Climate Assessment](https://montanaclimate.org/chapter/climate-change) being developed by the Montana Climate Office. The update to the assessment provides a summary of historical climate conditions across the state (@sec-historical), as well as an overview of projected changes in Montana's climate given different climate change scenarios (@sec-future). To assess historical climate conditions, we are using [NClimGrid](https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00332) climate data instead of NOAA's [station-based climate normals](https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals) used in the original version. We choose to use NClimGrid because it is spatially continuous across Montana and we have found it to have high accuracy relative to [Montana Mesonet](https://climate.umt.edu/mesonet/) weather stations. Using NClimGrid allows us to provide an accurate and high-resolution assessment of Montana's historical climate conditions. 

To summarize future climate projections, we use data from the sixth version of the Coupled Model Intercomparison Project (CMIP6), whereas the original assessment used CMIP5 projections. Specifically, we use an ensemble of eight models that have been spatially downscaled by the [NASA NEX-GDDP](https://www.nccs.nasa.gov/services/data-collections/land-based-products/nex-gddp-cmip6) project. The ensemble of eight models has been shown to best represent North America's future climate downscaled project ensemble of 8 models that perform well over North America [(https://eartharxiv.org/repository/view/2510/)](https://eartharxiv.org/repository/view/2510/). While CMIP6 projections are similar to the CMIP5 projections used in the original climate assessment, there are two notable differences:

1. **Different Downscaling Methods.** Both the original climate assessment and the update presented here use downscaled CMIP projections. The standard outputs of CMIP models are very coarse in spatial resolution, making it difficult to analyze their output at the county or even state scale. To overcome this issue, statistical methods can be applied to the coarse data to spatially downscale the models to a finer spatial resolution. The original climate assessment used projections downscaled with the [Multivariate Adaptive Constructed Analogs (MACA)](https://www.climatologylab.org/maca.html) method, whereas this update uses projections downscaled with the [Bias-Correction Spatial Disaggregation (BCSD)](https://www.nccs.nasa.gov/sites/default/files/NEX-GDDP-CMIP6-Tech_Note.pdf) method. While the results in both the original climate assessment and our update are similar, it is important to note that these two different downscaling methods were used. 
2. **Different Climate Scenarios.** In CMIP5 climate projections, future climate scenarios were provided as Representative Concentration Pathways (RCPs). In short, RCPs simulated the amount of warming that would occur given different increases in global CO<sub>2</sub> concentrations. The CMIP6 projections use a similar grouping of scenarios called Shared Socioeconomic Pathways (SSPs; explained in detail in @sec-future). SSPs take a more holistic approach to future emissions scenarios and incorporate information on how changes in the global economy, politics, and population are likely to affect CO<sub>2</sub> emissions. In this analysis, we use the SSP1-2.6, SSP2-4.5, SSP3-7.0 and SSP5-8.5 scenarios to summarize Montana's future climate projections. These scenarios encompass the full range of climate change scenarios we might expect by the end of the century. 
3. **Different Reference Period.** The original climate assessment compared future climate conditions to a reference period of 1981 to 2010. In climate science, it is common practice to update reference periods used for comparison with future projections each decade. As such, we have updated the reference period used in this analysis to the years 1991 to 2020. 

Like the original climate assessment, this assessment also uses Montana's climate divisions to summarize future climate conditions, with plans to summarize results at the county and watershed scale in the future. 

## Importance

Understanding current climate change and projecting future climate trends are of vital importance–both for our economy and our well-being. It is our goal to provide science-based information that serves as a resource for residents of `r params$location` who are interested in understanding `r params$location`’s climate and its impacts on water, agricultural lands and forests. To provide this understanding, we can learn from past climate trends. However, knowledge of the past is only partially sufficient in preparing for a future defined by unprecedented levels of greenhouse gases in the atmosphere. Therefore, we also provide projections of change into the future using today’s best scientific information and modeling techniques.

## Key Messages
Annual average temperatures, including daily minimums, maximums, and averages, have risen across the state between 1950 and 2015. The average temperature increase between 1951 and 2015 across Montana was 1.92°F

Winter and spring in Montana have experienced the most warming. Average temperatures during these seasons have risen by 3.4°F between 1950 and 2015.

Montana’s growing season length is increasing due to the earlier onset of spring and more extended summers; we are also experiencing more warm days and fewer cool nights. From **1951-2010**, the growing season increased by **12** days. In addition, the annual number of warm days has increased by **2.0%** and the annual number of cool nights has decreased by **4.6%** over this period.

Despite no historical changes in average annual precipitation between 1950 and 2015, there have been changes in average seasonal precipitation over the same period. Average winter precipitation has decreased by 0.96 inches, which can mostly be attributed to natural variability and an increase in El Niño events, especially in the western and central parts of the state. A significant increase in spring precipitation (1.34-1.98 inches) has also occurred during this period for the eastern portion of the state.

The state of Montana is projected to continue to warm in all geographic locations, seasons, and under all emission scenarios throughout the 21st century. By mid century, Montana temperatures are projected to increase by approximately 3.6-5.5°F depending on the emission scenario. By the end-of-century, Montana temperatures are projected to increase 3.7-9.2°F depending on the emission scenario.

The number of days in a year when daily temperature exceeds 90°F (32°C) and the number of frost-free days are expected to increase across the state and in both emission scenarios studied. Increases in the number of days above 90°F (32°C) are expected to be greatest in the eastern part of the state. Increases in the number of frost-free days are expected to be greatest in the western part of the state.

Across the state, precipitation is projected to increase in winter, spring, and fall; precipitation is projected to decrease in summer. The largest increases are expected to occur during spring in the southern part of the state. The largest decreases are expected to occur during summer in the central and eastern parts of the state. 

## Climate Change Defined
The US Global Change Research Program (@cc_def) defines climate change as follows:

> “Changes in average weather conditions that persist over multiple decades or longer. Climate change encompasses both increases and decreases in temperature, as well as shifts in precipitation, changing risk of certain types of severe weather events, and changes to other features of the climate system.”

## Outline
This document focuses on three areas:

1. providing a baseline summary of climate and climate change for Montana—with a focus on changes in temperature, precipitation, and extreme events—including reviewing the fundamentals of climate change science;

2. reviewing historical trends in Montana’s climate, and what those trends reveal about how our climate has changed in the past century, changes that are potentially attributable to world-wide increases in greenhouse gases; and

3. considering what today’s best available climate models project regarding Montana’s future, and how certain we can be in those projections.

This chapter serves as a foundation for the Montana Climate Assessment, providing information on present-day climate and climate terminology, past climate trends, and future climate projections. This foundation then serves as the basis for analyzing three key sectors of Montana—water, forests, and agriculture—considered in the other chapters of this assessment. In the sections below, we introduce the climate science and discuss important fundamental processes that determine whether climate remains constant or changes.
